# Importing Pandas and Reading JSON File

In [67]:
import pandas as pd

df = pd.read_json(r"D:\delhi_metro_analysis\a_source_data\a_delhi_metro_trips.json")
print(df.head(10))
print("The json dataset has been successfully loaded")

   TripID       Date         From_Station            To_Station  Distance_km  \
0   59771 2022-05-08             Inderlok         Kashmere Gate        12.94
1   21363 2023-01-12           Model Town        Dilshad Garden         2.33
2  127325 2023-07-13     Kashmere Gate     Netaji Subhash Place         5.56
3  140510 2022-11-10        Chandni Chowk             Hauz Khas         4.02
4  144298 2022-11-06          Rajiv Chowk        Kalkaji Mandir         9.66
5   96371 2024-07-10       Kalkaji Mandir          Shivaji Park         3.91
6   49743 2022-09-02          Mandi House          Jasola Vihar         1.49
7   47390 2023-12-07          Mandi House   Central Secretariat         7.38
8   58379 2024-05-05                AIIMS         Chandni Chowk         2.57
9   69048 2022-07-05            New Delhi          Jasola Vihar         7.58

     Fare  Cost_per_passenger  Passengers   Ticket_Type      Remarks
0   77.99               18.27        13.0    Smart Card  maintenance
1   35.89               83.71        15.0  Tourist Card  maintenance
2   64.35               43.70         9.0        Single     off-peak
3  144.13               14.98        27.0          None  maintenance
4  104.96               83.84        23.0        Single     off-peak
5   29.20               30.64        22.0  Tourist Card         None
6  175.32               33.45        14.0  Tourist Card         peak
7  167.59               50.69        18.0  Tourist Card     festival
8  125.25               81.71        24.0        Single      weekend
9  151.39               37.76        19.0  Tourist Card         peak
The json dataset has been successfully loaded

# df.info() Gives Summary of the DataFrame

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          9910 non-null   float64
 8   Ticket_Type         9888 non-null   object
 9   Remarks             8246 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 859.4+ KB

# Revoming Extra Spaces in Station_Names using .Strip() method and Standardizing Station_Names

In [69]:
df["From_Station"] = df["From_Station"].str.strip().str.replace(r"\s+", " ", regex= True).str.upper()
print(df["From_Station"])
df["To_Station"] = df["To_Station"].str.strip().str.replace(r"\s+", " ", regex= True).str.upper()
print(df["To_Station"])
df.head()

0                INDERLOK
1              MODEL TOWN
2           KASHMERE GATE
3           CHANDNI CHOWK
4             RAJIV CHOWK
              ...
9995          RAJIV CHOWK
9996       KALKAJI MANDIR
9997            HAUZ KHAS
9998          RAJIV CHOWK
9999    NOIDA CITY CENTRE
Name: From_Station, Length: 10000, dtype: object
0              KASHMERE GATE
1             DILSHAD GARDEN
2       NETAJI SUBHASH PLACE
3                  HAUZ KHAS
4             KALKAJI MANDIR
                ...
9995            SHIVAJI PARK
9996             KIRTI NAGAR
9997     CENTRAL SECRETARIAT
9998               OLD DELHI
9999          JANAKPURI WEST
Name: To_Station, Length: 10000, dtype: object

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,INDERLOK,KASHMERE GATE,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,MODEL TOWN,DILSHAD GARDEN,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,KASHMERE GATE,NETAJI SUBHASH PLACE,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,CHANDNI CHOWK,HAUZ KHAS,4.02,144.13,14.98,27.0,None,maintenance
4,144298,2022-11-06,RAJIV CHOWK,KALKAJI MANDIR,9.66,104.96,83.84,23.0,Single,off-peak

# Handling Missing Values

In [70]:
print(df["Ticket_Type"].isnull().sum())
print(df["Ticket_Type"].unique())
df["Ticket_Type"] = df["Ticket_Type"].fillna(df["Ticket_Type"].mode()[0])

print(df["Passengers"].isnull().sum())
print(df["Passengers"].unique())
df["Passengers"] = df["Passengers"].fillna(df["Passengers"].median())

print(df["Remarks"].isnull().sum())
print(df["Remarks"].unique())
df["Remarks"] = df["Remarks"].fillna(df["Remarks"].mode()[0])

112
['Smart Card' 'Tourist Card' 'Single' None]
90
[13. 15.  9. 27. 23. 22. 14. 18. 24. 19. 16. 21. 11. 26. 25. 28. 20. 17.
 31. 12.  8. 32. 34. 33. 35. 29. 30. nan 10.  7.  5. 36. 37.]
1754
['maintenance' 'off-peak' None 'peak' 'festival' 'weekend']

# Converting Date columns into DateTime Format

In [71]:
df["Date"].dtypes
df.info()
df.head()
# There is no requirement to convert because Date column is in DateTime Format

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   TripID              10000 non-null  int64
 1   Date                10000 non-null  datetime64[ns]
 2   From_Station        10000 non-null  object
 3   To_Station          10000 non-null  object
 4   Distance_km         10000 non-null  float64
 5   Fare                10000 non-null  float64
 6   Cost_per_passenger  10000 non-null  float64
 7   Passengers          10000 non-null  float64
 8   Ticket_Type         10000 non-null  object
 9   Remarks             10000 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(1), object(4)
memory usage: 859.4+ KB

,TripID,Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,INDERLOK,KASHMERE GATE,12.94,77.99,18.27,13.0,Smart Card,maintenance
1,21363,2023-01-12,MODEL TOWN,DILSHAD GARDEN,2.33,35.89,83.71,15.0,Tourist Card,maintenance
2,127325,2023-07-13,KASHMERE GATE,NETAJI SUBHASH PLACE,5.56,64.35,43.70,9.0,Single,off-peak
3,140510,2022-11-10,CHANDNI CHOWK,HAUZ KHAS,4.02,144.13,14.98,27.0,Tourist Card,maintenance
4,144298,2022-11-06,RAJIV CHOWK,KALKAJI MANDIR,9.66,104.96,83.84,23.0,Single,off-peak

# Changing Column Name

In [72]:
df.rename({"Date":"Jounery_Date"},axis=1,inplace=True)

# Ensuring Numeric Columns are Correctly Formatted

In [73]:
# Converting Passengers from Float dtype to Int dtype
df["Passengers"] = df["Passengers"].round().astype(int)
df.head()

,TripID,Jounery_Date,From_Station,To_Station,Distance_km,Fare,Cost_per_passenger,Passengers,Ticket_Type,Remarks
0,59771,2022-05-08,INDERLOK,KASHMERE GATE,12.94,77.99,18.27,13,Smart Card,maintenance
1,21363,2023-01-12,MODEL TOWN,DILSHAD GARDEN,2.33,35.89,83.71,15,Tourist Card,maintenance
2,127325,2023-07-13,KASHMERE GATE,NETAJI SUBHASH PLACE,5.56,64.35,43.70,9,Single,off-peak
3,140510,2022-11-10,CHANDNI CHOWK,HAUZ KHAS,4.02,144.13,14.98,27,Tourist Card,maintenance
4,144298,2022-11-06,RAJIV CHOWK,KALKAJI MANDIR,9.66,104.96,83.84,23,Single,off-peak

# Converting From JSON File To CSV File

In [74]:
# From JSON 
#df = pd.read_json(r"D:\delhi_metro_analysis\delhi_metro_trips.json")
# To Cleaned CSV
df_cleaned = df.copy()
df_cleaned.to_csv(r"D:\delhi_metro_analysis\b_cleaned_data\b_delhi_metro_trips.csv", index=False)
print("Data is Cleaned and Converted Into CVS File Successfully")

Data is Cleaned and Converted Into CVS File Successfully

# Database Creation (SQL)

In [75]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\Niharika\AppData\Local\Programs\Python\Python313\Lib\site-packages (8.1.0)
Requirement already satisfied: protobuf<=4.21.12,>=4.21.1 in c:\Users\Niharika\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mysql-connector-python) (4.21.12)
Note: you may need to restart the kernel to use updated packages.

In [76]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley"
)

if conn.is_connected():
    print("Connection Successful!")  

cursor = conn.cursor() 
cursor.execute("CREATE DATABaSE IF NOT EXISTS delhi_metro")

cursor.close()
conn.close()

Connection Successful!

In [77]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro",
    allow_local_infile=True
)  

cursor = conn.cursor
print("Connected to delhi_metro database")

Connected to delhi_metro database

# Creating a Structured table Schema

In [78]:
#database="delhi_metro"

cursor=conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS metro_trips(
    TripID INT,
    Journey_Date DATETIME,
    From_Station VARCHAR(50),
    To_Station VARCHAR(50),
    Distance_km FLOAT,
    Fare FLOAT,
    Cost_per_passenger FLOAT,
    Passengers INT,
    Ticket_Type VARCHAR(50),
    Remarks VARCHAR(100)
    )              
 """)

conn.commit()

# Importing cleaned data into the SQL table

In [79]:
# Convert dataframe to list of tuples

import pandas as pd
import mysql.connector

# Load CSV
df = pd.read_csv(r"D:\delhi_metro_analysis\b_cleaned_data\b_delhi_metro_trips.csv")

#check data
print(df.head())

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)
cursor = conn.cursor()

data = list(df.itertuples(index=False, name=None))

query = """
INSERT INTO metro_trips(
    TripID,
    Journey_Date,
    From_Station,
    To_Station,
    Distance_km,
    Fare,
    Cost_per_passenger,
    Passengers,
    Ticket_Type,
    Remarks
)
VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

cursor.executemany(query, data)
conn.commit()

print("Data inserted successfully!")

   TripID Jounery_Date   From_Station            To_Station  Distance_km  \
0   59771   2022-05-08       INDERLOK         KASHMERE GATE        12.94
1   21363   2023-01-12     MODEL TOWN        DILSHAD GARDEN         2.33
2  127325   2023-07-13  KASHMERE GATE  NETAJI SUBHASH PLACE         5.56
3  140510   2022-11-10  CHANDNI CHOWK             HAUZ KHAS         4.02
4  144298   2022-11-06    RAJIV CHOWK        KALKAJI MANDIR         9.66

     Fare  Cost_per_passenger  Passengers   Ticket_Type      Remarks
0   77.99               18.27          13    Smart Card  maintenance
1   35.89               83.71          15  Tourist Card  maintenance
2   64.35               43.70           9        Single     off-peak
3  144.13               14.98          27  Tourist Card  maintenance
4  104.96               83.84          23        Single     off-peak
Data inserted successfully!

# Creating Indexes for Faster Query Execution

In [80]:
#cursor.execute("""
#CREATE INDEX idx_Tripss
#ON metro_trips (TripID)             
#""")

#cursor.execute("""
#CREATE INDEX IF NOT EXISTS idx_Stations_Search
#ON metro_trips (From_Station, To_Station, Journey_Date)
#""")

#cursor.execute("""
#CREATE INDEX IF NOT EXISTS idx_Journey_Dates
#ON metro_trips (Journey_Date)             
#""")

#cursor.execute("""
#CREATE INDEX IF NOT EXISTS idx_Ticket_Types
#ON metro_trips (Ticket_Type)             
#""")

#cursor.execute("""
#CREATE INDEX IF NOT EXISTS idx_Passengerss
#ON metro_trips (Passengers)             
#""")

#cursor.execute("""
#CREATE INDEX IF NOT EXISTS idx_Remarkss
#ON metro_trips (Remarks)             
#""")

#conn.commit()

In [81]:
#cursor.execute("SHOW INDEX FROM metro_trips")
#for row in cursor.fetchall():
#    print(row[2])   # index name

In [82]:
#cursor.execute("SHOW INDEX FROM metro_trips")
#indexes = set([row[2] for row in cursor.fetchall()])

#for idx in indexes:
#    if idx != "PRIMARY":
#        cursor.execute(f"DROP INDEX {idx} ON metro_trips")

#conn.commit()
#print("All non-primary indexes dropped")

In [83]:
#import mysql.connector

#conn = mysql.connector.connect(
#   host="localhost",
#    user="root",
#    password="sakiley",
#    database="delhi_metro"
#)

#cursor = conn.cursor()

#cursor.execute("""
#ALTER TABLE metro_trips
#DROP INDEX idx_Trip,
#DROP INDEX idx_Station_Search,
#DROP INDEX idx_Journey_Date,
#DROP INDEX idx_Ticket_Type,
#DROP INDEX idx_Passengers,
#DROP INDEX idx_Remarks,
#DROP INDEX idx_TripS,
#DROP INDEX idx_Tripss,
#DROP INDEX idx_Stations_Search,
#DROP INDEX idx_Journey_Dates,
#DROP INDEX idx_Ticket_Types,
#DROP INDEX idx_Passengerss,
#DROP INDEX idx_Remarkss
#""")

#conn.commit()

In [84]:
cursor.execute("SHOW INDEX FROM metro_trips")
existing_indexes = [row[2] for row in cursor.fetchall()]

if "idx_route" not in existing_indexes:
    cursor.execute("CREATE INDEX idx_route ON metro_trips (From_Station, To_Station)")
if "idx_journey_date" not in existing_indexes:
    cursor.execute("CREATE INDEX idx_journey_date ON metro_trips (Journey_Date)")
if "idx_ticket" not in existing_indexes:
    cursor.execute("CREATE INDEX idx_ticket ON metro_trips (Ticket_Type)")

conn.commit()

# Data Analysis Using SQL

# Route Analysis

1.Which metro routes have the highest passenger traffic?

In [85]:
import pandas as pd

df = pd.read_sql_query("""
SELECT 
    From_Station,
    To_Station,
    SUM(Passengers) as total_passengers
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY total_passengers DESC
LIMIT 5;    
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\4220151137.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

  From_Station         To_Station  total_passengers
0  RAJIV CHOWK      CHANDNI CHOWK           36918.0
1  RAJIV CHOWK          OLD DELHI           33831.0
2  RAJIV CHOWK  NOIDA CITY CENTRE           33705.0
3  RAJIV CHOWK        KIRTI NAGAR           33033.0
4  RAJIV CHOWK       JASOLA VIHAR           32760.0

2.Which routes generate the highest total revenue?

In [86]:
import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    To_Station,
    Sum(Fare * Passengers) as total_revenue
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY total_revenue DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2582124677.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

  From_Station      To_Station  total_revenue
0  RAJIV CHOWK   CHANDNI CHOWK   4.131892e+06
1  RAJIV CHOWK  KALKAJI MANDIR   3.452798e+06
2  RAJIV CHOWK       OLD DELHI   3.445902e+06
3  RAJIV CHOWK       HAUZ KHAS   3.412430e+06
4  RAJIV CHOWK           AIIMS   3.400630e+06

3.What is the average fare for each route?

In [87]:
import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    To_Station,
    AVG(Fare) as average_fare
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY average_fare DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\1211053071.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

     From_Station      To_Station  average_fare
0     LAXMI NAGAR     LAXMI NAGAR    167.983332
1  DILSHAD GARDEN  DILSHAD GARDEN    153.259995
2       HAUZ KHAS  PRAGATI MAIDAN    140.597692
3   CHANDNI CHOWK     LAXMI NAGAR    140.508000
4        INDERLOK      MODEL TOWN    134.576818

4.Which routes have the longest travel distances?

In [88]:
import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    To_Station,
    MAX(Distance_km) as maximum_distance
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY maximum_distance DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\1692512676.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

     From_Station      To_Station  maximum_distance
0       NEW DELHI     MANDI HOUSE             45.69
1       HAUZ KHAS  DILSHAD GARDEN             43.94
2      MODEL TOWN     MANDI HOUSE             43.38
3  JANAKPURI WEST     LAXMI NAGAR             42.49
4     MANDI HOUSE       HAUZ KHAS             40.23

# Station Analysis

5.Which stations have the highest number of trip departures?

In [89]:
import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    COUNT(From_Station) as count_of_maximum_departures
FROM metro_trips
GROUP BY From_Station
ORDER BY count_of_maximum_departures DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\1496272098.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

        From_Station  count_of_maximum_departures
0        RAJIV CHOWK                        35574
1  NOIDA CITY CENTRE                        25977
2          NEW DELHI                        17598
3        MANDI HOUSE                        17472
4      CHANDNI CHOWK                         9450

5.a.Total departure analysis:

In [90]:

import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()


import pandas as pd

df = pd.read_sql_query("""
SELECT
    station,
    SUM(departures) as total_departures,
    SUM(arrivals) as total_arrivals
FROM(
    SELECT From_Station as station, COUNT(*) as departures, 0 as arrivals
    FROM metro_trips
    GROUP BY From_Station
                       
UNION
    
    SELECT To_Station as station, 0 as arrivals, COUNT(*) as arrrival
    FROM metro_trips
    GROUP BY To_Station
)AS combined
GROUP BY station
ORDER BY total_departures DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\277196075.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

             station  total_departures  total_arrivals
0        RAJIV CHOWK           35574.0          8064.0
1  NOIDA CITY CENTRE           25977.0          8883.0
2          NEW DELHI           17598.0          8505.0
3        MANDI HOUSE           17472.0          8757.0
4      CHANDNI CHOWK            9450.0          9114.0

6. Which stations receive the highest number of passengers?

In [91]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor

import pandas as pd

df = pd.read_sql_query("""
SELECT
    To_Station,
    SUM(Passengers) as maximum_passengers
FROM metro_trips
GROUP BY To_Station
ORDER BY maximum_passengers DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\3131274981.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

        To_Station  maximum_passengers
0     JASOLA VIHAR            190974.0
1      LAXMI NAGAR            189609.0
2    CHANDNI CHOWK            185850.0
3   RAJOURI GARDEN            184737.0
4  BARAKHAMBA ROAD            184485.0

7. What are the top 10 most frequently used metro stations?

In [92]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    station,
    SUM(total_passengers) AS total_usage
FROM (
    SELECT From_Station AS station, SUM(Passengers) AS total_passengers
    FROM metro_trips
    GROUP BY From_Station

    UNION ALL

    SELECT To_Station AS station, SUM(Passengers) AS total_passengers
    FROM metro_trips
    GROUP BY To_Station
) AS combined
GROUP BY station
ORDER BY total_usage DESC
LIMIT 10;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2640583614.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

             station  total_usage
0        RAJIV CHOWK     869253.0
1  NOIDA CITY CENTRE     696087.0
2        MANDI HOUSE     526239.0
3          NEW DELHI     524160.0
4      CHANDNI CHOWK     377538.0
5        LAXMI NAGAR     368235.0
6           INDERLOK     367269.0
7       JASOLA VIHAR     365841.0
8     KALKAJI MANDIR     356664.0
9              AIIMS     353199.0

8. Which station pairs are most frequently used for travel?

In [93]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    To_Station,
    SUM(Passengers) as frequently_travelled
FROM metro_trips
GROUP BY From_Station,To_Station
ORDER BY frequently_travelled DESC
LIMIT 10;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2414946039.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

  From_Station            To_Station  frequently_travelled
0  RAJIV CHOWK         CHANDNI CHOWK               36918.0
1  RAJIV CHOWK             OLD DELHI               33831.0
2  RAJIV CHOWK     NOIDA CITY CENTRE               33705.0
3  RAJIV CHOWK           KIRTI NAGAR               33033.0
4  RAJIV CHOWK          JASOLA VIHAR               32760.0
5  RAJIV CHOWK        JANAKPURI WEST               32067.0
6  RAJIV CHOWK                 AIIMS               32004.0
7  RAJIV CHOWK  NETAJI SUBHASH PLACE               31815.0
8  RAJIV CHOWK              INDERLOK               31521.0
9  RAJIV CHOWK        KALKAJI MANDIR               30975.0

# Revenue Analysis

9. What is the total revenue generated from all trips?

In [94]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT SUM(Passengers*Fare) as total_revenue
FROM metro_trips
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\3622585313.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   total_revenue
0   4.386771e+08

10. What is the average fare per trip?

In [95]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT
    TripID,
    AVG(Passengers*Fare) as average_fare
FROM metro_trips
GROUP BY TripID
ORDER BY average_fare
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2335755524.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   TripID  average_fare
0  131069    103.860000
1  136189    103.999996
2  111868    116.239998
3   93169    130.130003
4  119314    143.130003

11. Which routes generate the highest revenue per kilometer?

In [96]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT
    From_Station,
    To_Station,
    SUM(Passengers * Fare) / SUM(Distance_km) as revenue_per_km
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY revenue_per_km DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\3678066459.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

          From_Station       To_Station  revenue_per_km
0       DILSHAD GARDEN   DILSHAD GARDEN     6385.832851
1       KALKAJI MANDIR  BARAKHAMBA ROAD      955.695274
2  CENTRAL SECRETARIAT   PRAGATI MAIDAN      952.333351
3                AIIMS            AIIMS      767.579280
4             INDERLOK   DILSHAD GARDEN      705.914572

12. Which ticket type generates the highest revenue?

In [97]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT
    Ticket_Type,
    SUM(Passengers * Cost_per_passenger) as ticket_type_revenue
FROM metro_trips
GROUP BY Ticket_Type
ORDER BY ticket_type_revenue DESC
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\882802810.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

    Ticket_Type  ticket_type_revenue
0  Tourist Card         1.306005e+08
1        Single         6.748556e+07
2    Smart Card         6.596921e+07

# Passenger Analysis

13. What is the average number of passengers per trip?

In [98]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT AVG(Passengers) as average_passengers
FROM metro_trips
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\352590382.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

   average_passengers
0             20.0178

14. Which trips recorded the highest passenger counts?

In [99]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    From_Station,
    To_Station,                  
    SUM(Passengers) as max_passengers_count
FROM metro_trips
GROUP BY From_Station, To_Station
ORDER BY max_passengers_count DESC
LIMIT 5;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\650772021.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

  From_Station         To_Station  max_passengers_count
0  RAJIV CHOWK      CHANDNI CHOWK               36918.0
1  RAJIV CHOWK          OLD DELHI               33831.0
2  RAJIV CHOWK  NOIDA CITY CENTRE               33705.0
3  RAJIV CHOWK        KIRTI NAGAR               33033.0
4  RAJIV CHOWK       JASOLA VIHAR               32760.0

15. What is the passenger distribution by ticket type?

In [100]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    Ticket_Type,
    SUM(Passengers) AS total_passengers,
    (SUM(Passengers) * 100.0 / (SELECT SUM(Passengers) FROM metro_trips)) AS percentage_distribution
FROM metro_trips
GROUP BY Ticket_Type
ORDER BY total_passengers DESC;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\1590392111.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

    Ticket_Type  total_passengers  percentage_distribution
0  Tourist Card         2086266.0                 49.62883
1        Single         1065897.0                 25.35593
2    Smart Card         1051575.0                 25.01524

16. What is the total passenger count for each station?

In [101]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    From_Station,
    SUM(Passengers) AS total_passengers
FROM metro_trips
GROUP BY From_Station
ORDER BY total_passengers DESC;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\3312645206.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

           From_Station  total_passengers
0           RAJIV CHOWK          708288.0
1     NOIDA CITY CENTRE          517902.0
2           MANDI HOUSE          355026.0
3             NEW DELHI          352023.0
4         CHANDNI CHOWK          191688.0
5              INDERLOK          187341.0
6           LAXMI NAGAR          178626.0
7         KASHMERE GATE          177702.0
8                 AIIMS          177366.0
9            MODEL TOWN          176148.0
10         JASOLA VIHAR          174867.0
11       KALKAJI MANDIR          173775.0
12            HAUZ KHAS          172725.0
13       DILSHAD GARDEN          171969.0
14  CENTRAL SECRETARIAT          169764.0
15       JANAKPURI WEST          159411.0
16       RAJOURI GARDEN          159117.0

# Travel Pattern Analysis

17. How many trips occur during peak, off-peak, festival, and weekend conditions?

In [102]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    Remarks,
    COUNT(*) AS total_trips
FROM metro_trips
GROUP BY Remarks
ORDER BY total_trips DESC;
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2630461847.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

       Remarks  total_trips
0     festival        71967
1     off-peak        34755
2      weekend        34671
3  maintenance        34629
4         peak        33978

18. Which travel condition generates the highest revenue?

In [103]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    Remarks,
    SUM(Passengers * Cost_per_passenger) AS highest_revenue
FROM metro_trips
GROUP BY Remarks
ORDER BY highest_revenue DESC;   
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\3763339169.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

       Remarks  highest_revenue
0     festival     9.038791e+07
1      weekend     4.409797e+07
2     off-peak     4.395344e+07
3  maintenance     4.323417e+07
4         peak     4.238176e+07

19. What is the monthly passenger trend across the dataset?

In [104]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    MONTHNAME(Journey_Date) AS month,
    SUM(Passengers) AS monthly_trend
FROM metro_trips
GROUP BY MONTHNAME(Journey_Date)
ORDER BY monthly_trend DESC;   
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\244357845.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

        month  monthly_trend
0     January       366954.0
1       April       364959.0
2         May       362292.0
3    December       361704.0
4        July       359583.0
5   September       357231.0
6     October       346605.0
7      August       344379.0
8       March       342951.0
9    February       334719.0
10       June       332220.0
11   November       330141.0

20. Which travel condition has the highest average passenger count per trip?

In [105]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="sakiley",
    database="delhi_metro"
)  

cursor = conn.cursor()

import pandas as pd

df = pd.read_sql_query("""
SELECT 
    Remarks,
    AVG(Passengers) AS highest_avg_passengers
FROM metro_trips
GROUP BY Remarks
ORDER BY highest_avg_passengers DESC;                    
""", conn)

print(df)

C:\Users\Niharika\AppData\Local\Temp\ipykernel_19920\2094572823.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("""

       Remarks  highest_avg_passengers
0     off-peak                 20.2211
1     festival                 20.0131
2  maintenance                 19.9921
3         peak                 19.9506
4      weekend                 19.9152